name: SAST + Deploy Frontend & Backend

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  # --- SAST (CodeQL + Semgrep) ---
  sast:
    name: SAST (CodeQL + Semgrep)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # needed for uploading SARIF
      actions: read
    steps:
      - uses: actions/checkout@v4

      # CodeQL for JavaScript/TypeScript
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript
          queries: security-and-quality

      - name: CodeQL Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: CodeQL Analyze
        uses: github/codeql-action/analyze@v3
        with:
          category: "monorepo-js"

      # Semgrep CLI (explicit SARIF output)
      - name: Install Semgrep
        run: |
          python3 -m pip install --upgrade pip
          pip3 install semgrep

      - name: Run Semgrep and generate SARIF
        run: |
          semgrep --version
          # Add/remove configs as you like; p/ci is a good default
          semgrep --config p/ci --config p/javascript --sarif --output semgrep.sarif

      - name: Upload Semgrep SARIF to
