name: SAST + Deploy Frontend & Backend

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  # --- SAST job (CodeQL + Semgrep CLI) ---
  sast:
    name: SAST (CodeQL + Semgrep)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # required to upload SARIF to Code Scanning
      actions: read
    steps:
      - uses: actions/checkout@v4

      # --- CodeQL (JavaScript/TypeScript) ---
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript
          queries: security-and-quality

      - name: CodeQL Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: CodeQL Analyze
        uses: github/codeql-action/analyze@v3
        with:
          category: "monorepo-js"

      # --- Semgrep (CLI, explicit SARIF) ---
      - name: Install Semgrep
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade semgrep

      - name: Semgrep scan (generate SARIF)
        # Use remote rulesets; adjust/add configs as needed
        run: |
          semgrep ci \
            --config p/ci \
            --config p/javascript \
            --sarif -o semgrep.sarif \
          || true

      - name: Upload Semgrep SARIF to Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

  # Detect which part changed
  changes:
    runs-on: ubuntu-latest
    needs: sast
    outputs:
      client: ${{ steps.filter.outputs.client }}
      server: ${{ steps.filter.outputs.server }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            client:
              - 'client/**'
            server:
              - 'server/**'

  # --- Frontend: Vercel (no .vercel file, no linking required) ---
  frontend:
    if: needs.changes.outputs.client == 'true'
    needs: changes
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: vercel-frontend-prod
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: client/package-lock.json

      # Optional local build to catch errors early
      - name: Install deps (client)
        run: npm ci
        working-directory: client

      - name: Build (client)
        run: npm run build
        working-directory: client

      # Deploy via Vercel CLI WITHOUT .vercel/project.json.
      # Provide IDs via env and run inside /client.
      - name: Deploy to Vercel (prebuilt)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # required
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }} # team slug or ID (as used in your org)
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} # prj_…
        run: |
          npm i -g vercel@latest
          vercel pull --yes --environment=production \
            --token="$VERCEL_TOKEN" \
            --scope="$VERCEL_ORG_ID" \
            --cwd client
          vercel build --prod \
            --token="$VERCEL_TOKEN" \
            --cwd client
          vercel deploy --prebuilt --prod \
            --token="$VERCEL_TOKEN" \
            --scope="$VERCEL_ORG_ID" \
            --cwd client

  # --- Backend: Render (trigger deploy) ---
  backend:
    if: needs.changes.outputs.server == 'true'
    needs: changes
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: render-backend-prod
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Trigger Render deploy
        run: |
          curl -fsS -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/json" \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
