name: SAST + Deploy Frontend & Backend

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  # --- SAST (CodeQL + Semgrep) ---
  sast:
    name: SAST (CodeQL + Semgrep)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript
          queries: security-and-quality

      - name: CodeQL Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: CodeQL Analyze
        uses: github/codeql-action/analyze@v3
        with:
          category: monorepo-js

      - name: Install Semgrep
        run: |
          python3 -m pip install --upgrade pip
          pip3 install semgrep

      - name: Run Semgrep and generate SARIF
        run: |
          semgrep --version
          semgrep --config p/ci --config p/javascript --sarif --output semgrep.sarif

      - name: Upload Semgrep SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

  # --- Detect which side changed ---
  changes:
    runs-on: ubuntu-latest
    needs: sast
    outputs:
      client: ${{ steps.filter.outputs.client }}
      server: ${{ steps.filter.outputs.server }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            client:
              - 'client/**'
            server:
              - 'server/**'

  # --- Frontend deploy: Vercel (no .vercel linking) ---
  frontend:
    if: needs.changes.outputs.client == 'true'
    needs: changes
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: vercel-frontend-prod
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install deps (client)
        run: npm ci
        working-directory: client

      - name: Build (client)
        run: npm run build
        working-directory: client

      - name: Deploy to Vercel (prebuilt)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # required
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }} # team_… or user_…
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} # prj_…
        run: |
          npm i -g vercel@latest
          vercel pull --yes --environment=production \
            --token="$VERCEL_TOKEN" \
            --scope="$VERCEL_ORG_ID" \
            --cwd client
          vercel build --prod \
            --token="$VERCEL_TOKEN" \
            --cwd client
          vercel deploy --prebuilt --prod \
            --token="$VERCEL_TOKEN" \
            --scope="$VERCEL_ORG_ID" \
            --cwd client

  # --- Backend deploy: Render (trigger via API) ---
  backend:
    if: needs.changes.outputs.server == 'true'
    needs: changes
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: render-backend-prod
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Render deploy
        run: |
          curl -fsS -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/json" \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
